// <auto-generated />
using LoomPipe.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoomPipe.Storage.Migrations
{
    [DbContext(typeof(LoomPipeDbContext))]
    [Migration("20260122004453_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("LoomPipe.Core.Entities.DataSourceConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataSourceConfigs");
                });

            modelBuilder.Entity("LoomPipe.Core.Entities.FieldMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AutomapScore")
                        .HasColumnType("REAL");

                    b.Property<string>("DestinationField")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAutomapped")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PipelineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceField")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PipelineId");

                    b.ToTable("FieldMap");
                });

            modelBuilder.Entity("LoomPipe.Core.Entities.Pipeline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DestinationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceId")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Transformations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("SourceId");

                    b.ToTable("Pipelines");
                });

            modelBuilder.Entity("LoomPipe.Core.Entities.FieldMap", b =>
                {
                    b.HasOne("LoomPipe.Core.Entities.Pipeline", null)
                        .WithMany("FieldMappings")
                        .HasForeignKey("PipelineId");
                });

            modelBuilder.Entity("LoomPipe.Core.Entities.Pipeline", b =>
                {
                    b.HasOne("LoomPipe.Core.Entities.DataSourceConfig", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoomPipe.Core.Entities.DataSourceConfig", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("LoomPipe.Core.Entities.Pipeline", b =>
                {
                    b.Navigation("FieldMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
